version: '3'

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    hostname: proxy.domain.ru
    volumes:
      - "./db/:/etc/x-ui/"
      - "/etc/letsencrypt/live/proxy.domain.ru/fullchain.pem:/root/cert/fullchain.pem"
      - "/etc/letsencrypt/live/proxy.domain.ru/privkey.pem:/root/cert/privkey.pem"
      - "./logs/:/var/log/"
      - fail2ban:/etc/fail2ban/
      #- "./logs/access.log:/app/access.log"
      #- "./logs/error.log:/app/error.log"
    environment:
      #TZ: "Europe/Amsterdam"
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
volumes:
  fail2ban: {}
